<?php

Class RoomsMiddleware {
 
public function index(){
    // AQUÍ PUEDES AGREGAR LÓGICA DE AUTORIZACIÓN O CUALQUIER OTRA LÓGICA ANTES DE MOSTRAR LAS HABITACIONES
    // POR EJEMPLO, PODRÍAS VERIFICAR SI EL USUARIO TIENE PERMISO PARA VER LAS HABITACIONES

    // SI TODO ESTÁ BIEN, CARGAMOS LA VISTA DE HABITACIONES
    require APP_PATH . 'views/rooms/reservas.php';
    
}
}