USE `db_hotel`;
/* PROCEDURES STANDAR
    1. SP DE CONSULTAS      (LISTAR DATOS, OBTENER POR ID, ETC)
    2. SP DE INSERCIÓN      (INSERTAR NUEVOS REGISTROS)
    3. SP DE ACTUALIZACIÓN  (EDITAR REGISTROS EXISTENTES)
    4. SP DE ELIMINACIÓN    (ELIMINACION LÓGICA, CAMBIAR ESTADO A INACTIVO)
    
    TRIGGERS STANDARES
    1. TRIGGER DE AUDITORÍA (REGISTRAR FECHA DE CREACIÓN Y ACTUALIZACIÓN)
    2. TRIGGER DE VALIDACIÓN (VALIDAR DATOS ANTES DE INSERTAR O ACTUALIZAR)
    3. TRIGGER DE INTEGRIDAD (MANTENER LA INTEGRIDAD REFERENCIAL ENTRE TABLAS)
    4. TRIGGER DE NOTIFICACIÓN (ENVIAR NOTIFICACIONES O REALIZAR ACCIONES ADICIONALES DESPUÉS DE CIERTAS OPERACIONES)

    VISTAS STANDARES
    1. VISTA DE CONSULTA GENERAL (COMBINAR DATOS DE VARIAS TABLAS PARA CONSULTAS FRECUENTES)
    2. VISTA DE RESUMEN (RESUMEN DE DATOS PARA INFORMES O DASHBOARDS)
    3. VISTA DE DETALLE (DETALLES ESPECÍFICOS DE UN REGISTRO O CONJUNTO DE REGISTROS)
    4. VISTA DE FILTRADO (FILTRAR DATOS SEGÚN CRITERIOS ESPECÍFICOS PARA CONSULTAS ESPECIALIZADAS)
*/
 